# -*- coding: utf-8 -*-
"""Arsitektur Model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GM-Ah4-sN8Kv1IMlYT5gkK3mQR8KAWZR
"""

class Net1(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(784,256)
        self.fc2 = nn.Linear(256,128)
        self.fc3 = nn.Linear(128, 64)
        self.fc4 = nn.Linear(64,11)

        self.dropout = nn.Dropout(0.2)
        

    def forward(self, x):
        # one activated conv layer
        x = x.view(x.shape[0], -1)
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.dropout(F.relu(self.fc2(x)))
        x = self.dropout(F.relu(self.fc3(x)))
        x = F.log_softmax(self.fc4(x), dim=1)

        return x
cnn = Net1()